name: CreepyFreedomMod
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
version: ${tfm.build.version}
description: Plugin for the Creepy Freedom server.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, Essentials]
authors: [TheLastWind, AwesomePinch, _Radation]

# plugin.yml is no longer used to define commands.
